# Generated by Django 6.0.1 on 2026-01-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnderConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_under_construction', models.BooleanField(default=False)),
                ('uc_not', models.TextField(blank=True, help_text='Under Construction Notification Message', null=True)),
                ('uc_duration', models.DateTimeField(blank=True, help_text='End time for under construction', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
