# Generated by Django 6.0.1 on 2026-01-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='underconstruction',
            old_name='uc_not',
            new_name='uc_note',
        ),
    ]
