# Generated by Django 6.0.1 on 2026-01-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='pcate',
            field=models.CharField(max_length=255, verbose_name='Page Category'),
        ),
        migrations.AlterField(
            model_name='page',
            name='pname',
            field=models.CharField(max_length=255, verbose_name='Page Name'),
        ),
        migrations.AlterField(
            model_name='page',
            name='ppublished',
            field=models.DateField(verbose_name='Page Published Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ptcat',
            field=models.CharField(max_length=255, verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ptpublished',
            field=models.DateField(verbose_name='Post Published Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='song',
            name='sduration',
            field=models.IntegerField(verbose_name='Song Duration'),
        ),
        migrations.AlterField(
            model_name='song',
            name='stitle',
            field=models.CharField(max_length=255, verbose_name='Song Title'),
        ),
    ]
