# Generated by Django 6.0.1 on 2026-01-16 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_contractor_age_alter_student_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=100)),
                ('center_city', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('examcenter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.examcenter')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField(max_length=50)),
            ],
            bases=('core.examcenter',),
        ),
    ]
